'use strict';
let db=null, series={}, selected='BAMLH0A0HYM2';
const titles={overview:'자금의 흐름',credit:'신용시장',treasury:'재무부와 민간',funding:'AI 펀딩 경로',sources:'데이터 상태'};
const names={BAMLH0A0HYM2:'미국 하이일드 OAS',BAMLC0A0CM:'투자등급 OAS',BAMLH0A1HYBB:'BB OAS',BAMLH0A2HYB:'B OAS',BAMLH0A3HYC:'CCC 이하 OAS',H41_TOTAL_ASSETS:'연준 총자산',H41_RESERVES:'은행 지급준비금',H41_TGA:'재무부 TGA · 수요일',H41_RRP_TOTAL:'연준 전체 역레포',H41_NOTES:'연준권 순발행',H41_OTHER_LIABILITIES_CAPITAL:'기타 부채·자본',H41_TREASURIES:'연준 보유 국채',H41_MBS:'연준 보유 MBS',H8_CI_LOANS:'은행 C&I 대출 잔액',H8_NONBANK_LOANS:'은행의 비은행 금융기관 대출',H8_DEPOSITS:'은행 예금 잔액',RRPONTSYD:'국내 ON RRP',SOFR:'SOFR',IORB:'지준금리 IORB',DGS2:'미국 국채 2년',DGS10:'미국 국채 10년',DTS_TGA_CLOSE:'TGA 일별 마감 잔액',DTS_NET_CASH_BORROWING:'재무부 순현금차입',DTS_NONDEBT_WITHDRAWALS:'채무상환 제외 현금지출',DTS_TAX_CATEGORY_DEPOSITS:'세금 항목 입금',DRTSCILM:'C&I 대출기준 순강화 비율',DRSDCILM:'C&I 대출수요 순증가 비율',NCBTLLQ027S:'비금융기업 대출부채 거래 · 연율'};
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=u=>{try {const x=new URL(u);return ['https:','http:'].includes(x.protocol)?esc(x.href):'#';}catch{return '#';}};
const num=v=>v===null||v===undefined?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:2});
const display=r=>!r?'미수집':`${num(r.unit==='USD'?r.value/1e9:r.value)} ${r.unit==='USD'?'USD bn':esc(r.unit).replaceAll('_',' ')}`;
const label=id=>names[id]||id;
const latest=id=>series[id]?.filter(r=>r.value!==null).at(-1);
const sourceOf=r=>db.sources.find(s=>s.source===r?.source);
const state=s=>({ok:'수집 성공',partial:'일부 수집',failed:'수집 실패',error:'수집 실패',unavailable:'접근 불가'}[s?.status]||'미수집');
function card(id){const r=latest(id),s=sourceOf(r);return `<button class="metric" data-series="${esc(id)}"><span class="label">${esc(label(id))}</span><div class="value">${display(r)}</div><small>관측 ${esc(r?.date)} · ${state(s)}</small></button>`;}
const cards=ids=>`<div class="cards">${ids.map(card).join('')}</div>`;
const panel=(title,body,note='')=>`<section class="panel"><div class="panel-head"><h2>${esc(title)}</h2></div>${note?`<p class="subtitle">${esc(note)}</p>`:''}${body}</section>`;
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(c=>`<tr>${c.map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}">해당 데이터가 없습니다.</td></tr>`}</tbody></table></div>`;
function plot(id){const points=(series[id]||[]).filter(r=>r.value!==null).slice(-160);if(points.length<2)return '<div class="empty">차트를 그릴 관측값이 부족합니다.</div>';const vals=points.map(r=>r.value),low=Math.min(...vals),high=Math.max(...vals),span=high-low||1;const path=points.map((r,i)=>`${i?'L':'M'}${50+i/(points.length-1)*840},${180-(r.value-low)/span*140}`).join(' ');return `<svg class="chart" viewBox="0 0 960 220" role="img" aria-label="${esc(label(id))} 시계열"><text x="8" y="36">${num(high)}</text><text x="8" y="185">${num(low)}</text><path d="${path}" fill="none" stroke="#187c84" stroke-width="2.5"/><text x="50" y="215">${points[0].date}</text><text x="780" y="215">${points.at(-1).date}</text></svg><p class="help">최근 ${points.length}개 유효 관측 · ${esc(points.at(-1).unit)} · 결측값 제외</p>`;}
function overview(){const bridge=db.reserve_bridge;let bridgeHtml='<div class="empty">동일 기준일의 연준 대차대조표를 기다리는 중입니다.</div>';if(bridge){const max=Math.max(...Object.values(bridge.contributions).map(Math.abs),1);bridgeHtml=`<p class="subtitle">${bridge.previous_date} → ${bridge.date} · ${esc(bridge.unit)} · 감소한 부채는 준비금 증가 방향</p>${Object.entries(bridge.contributions).map(([id,v])=>`<div class="watch-row"><span>${esc(label(id))}<small style="width:${Math.abs(v)/max*200}px;max-width:100%;height:6px;background:${v>=0?'#187c84':'#b35b65'}"></small></span><b>${v>=0?'+':''}${num(v)}</b></div>`).join('')}<div class="simulation-output"><span>지급준비금 실제 변화</span><strong>${num(bridge.reserve_change)}</strong></div><p class="help">회계식 잔차 ${num(bridge.identity_residual)} · 기타 부채·자본은 잔액 차감으로 계산한 항목입니다.</p>`;}
return `<div class="insight"><span class="symbol">≋</span><div><b>연준 유동성 → 재무부·민간 중개 → 기업 자금조달</b><p>각 단계의 자료를 함께 관찰합니다. 총량 유동성 증가가 AI 기업의 자금 유입을 직접 입증하지는 않습니다.</p></div></div>${cards(['H41_TOTAL_ASSETS','H41_RESERVES','DTS_TGA_CLOSE','RRPONTSYD'])}${panel('지급준비금 변화의 구성',bridgeHtml)}${cards(['BAMLH0A0HYM2','BAMLC0A0CM','H8_NONBANK_LOANS','SOFR'])}${panel('하이일드 스프레드',plot('BAMLH0A0HYM2'))}`;}
function credit(){return `${cards(['BAMLH0A0HYM2','BAMLC0A0CM','BAMLH0A1HYBB','BAMLH0A3HYC'])}<div class="filter">${['BAMLH0A0HYM2','BAMLC0A0CM','BAMLH0A1HYBB','BAMLH0A2HYB','BAMLH0A3HYC'].map(id=>`<button class="${id===selected?'selected':''}" data-chart="${id}">${esc(label(id))}</button>`).join('')}</div>${panel(label(selected),plot(selected),'OAS 단위 bp. 시장 전체 신용위험 지표이며 AI 전용 스프레드가 아닙니다. MOVE는 수집 대상에서 제외했습니다.')}${cards(['SOFR','IORB','DGS2','DGS10'])}${panel('은행 신용 공급과 수요',cards(['H8_CI_LOANS','H8_NONBANK_LOANS','DRTSCILM','DRSDCILM']),'대출 잔액은 신규 실행액이 아닙니다. SLOOS는 분기 설문으로 일별 시장 지표와 공표 시차가 다릅니다.')}`;}
function treasury(){const auctions=db.events.filter(e=>e.event_type==='treasury_auction').sort((a,b)=>b.auction_date.localeCompare(a.auction_date)).slice(0,60);const mmf=Object.keys(series).filter(k=>k.startsWith('SEC_MMF_'));return `${cards(['DTS_TGA_CLOSE','DTS_NET_CASH_BORROWING','DTS_NONDEBT_WITHDRAWALS','DTS_TAX_CATEGORY_DEPOSITS'])}${panel('TGA 현금 잔액',plot('DTS_TGA_CLOSE'),'순현금차입은 전체 공공부채의 현금 발행−상환입니다. 국채 입찰 액면금액과 구분합니다.')}${panel('국채 입찰 · 최근 60건',table(['입찰일','결제일','종류 / 만기','모집액 bn','낙찰액 bn','응찰배율','상태'],auctions.map(e=>[esc(e.auction_date),esc(e.settlement_date),`<a href="${safeUrl(e.source_url)}" target="_blank" rel="noopener">${esc(e.security_type)} / ${esc(e.security_term)}</a>`,num(e.offering_amt_bn),num(e.total_accepted_bn),num(e.bid_to_cover_ratio),esc(e.status)])),'발표·낙찰·결제일을 구분합니다. 미래 입찰의 미공표 낙찰액은 — 로 표시합니다.')}${panel('MMF 보유자산 구성',mmf.length?cards(mmf):'<div class="empty">SEC N-MFP 데이터 미확보 · 데이터 상태 탭에서 원인을 확인하세요.</div>','공시 패키지 내 비피더 펀드의 보유자산입니다. 신규 자금 유입 또는 AI 투자 금액이 아닙니다.')}${cards(['H8_DEPOSITS','H8_NONBANK_LOANS','NCBTLLQ027S','RRPONTSYD'])}`;}
function factsTable(symbols){return table(['기업','보고 기간','영업현금흐름 bn','현금 CAPEX bn','OCF / CAPEX','장기차입 유입 bn'],symbols.map(symbol=>{const rows=db.observations.filter(r=>r.symbol===symbol&&r.series_id.includes('_CASH_CAPEX_'));rows.sort((a,b)=>b.date.localeCompare(a.date)||(b.duration_days-a.duration_days));const cap=rows[0];const fact=metric=>cap?db.observations.find(r=>r.symbol===symbol&&r.series_id.includes(`_${metric}_`)&&r.date===cap.date&&r.period_start===cap.period_start):null;return [esc(symbol),cap?`${cap.period_start} → ${cap.date}`:'미확보',num(fact('OCF')?fact('OCF').value/1e9:null),num(cap?cap.value/1e9:null),num(fact('CASH_COVERAGE')?.value),num(fact('DEBT_PROCEEDS')?fact('DEBT_PROCEEDS').value/1e9:null)];}));}
function bankCashTable(banks){const types={DEBT_PROCEEDS:'장기차입 현금유입',DEBT_CAPITAL_PROCEEDS_NET:'장기채무·자본증권 순발행 유입',SECURED_DEBT_PROCEEDS:'담보부 채무 발행 유입',UNSECURED_DEBT_PROCEEDS:'무담보 채무 발행 유입',AGGREGATE_BORROWING_PROCEEDS:'총차입 발행 유입'};const rows=[];for(const symbol of banks){for(const [metric,title] of Object.entries(types)){const facts=db.observations.filter(r=>r.symbol===symbol&&r.series_id.startsWith(`SEC_${symbol}_${metric}_`)).sort((a,b)=>b.date.localeCompare(a.date)||b.duration_days-a.duration_days);if(facts.length){const r=facts[0];rows.push([esc(symbol),esc(title),`${r.period_start} → ${r.date}`,num(r.value/1e9),`<a href="${safeUrl(r.source_url)}" target="_blank" rel="noopener">근거 ↗</a>`]);}}}return table(['은행','공시상 정의','보고 기간','USD bn','출처'],rows);}
function funding(){const candidates=db.events.filter(e=>e.event_type==='funding_candidate');const inv=db.events.filter(e=>e.event_type==='filing_inventory');const banks=['JPM','BAC','C','WFC','GS','MS'];return `<div class="flow"><div class="flow-col"><div class="node"><b>유동성 여건</b><p>준비금 · TGA · ON RRP</p></div></div><div class="flow-col"><div class="node"><b>민간 중개</b><p>은행 대출 · MMF 자산 · 채권시장</p></div></div><div class="flow-col"><div class="node"><b>AI 기업 조달과 지출</b><p>SEC 공시 · OCF · 현금 CAPEX</p></div></div></div><p class="flow-note">위 연결은 관찰 구조입니다. 특정 자금이 AI로 흘러갔다는 확인된 거래 연결을 의미하지 않습니다.</p>${panel('AI 관련 기업의 현금 CAPEX와 자체 조달력',factsTable(['MSFT','GOOGL','AMZN','META','ORCL','CRWV']),'각 기업 연결 기준입니다. AI 투자만 분리된 수치가 아니며, 같은 시작일·종료일의 보고 기간끼리만 비교합니다. 리스·비현금 투자와 가이던스는 포함하지 않습니다. AMZN은 소프트웨어 등을 포함한 생산자산 현금 취득 기준입니다.')}${panel('은행 현금 조달 규모',bankCashTable(banks),'보고서의 현금흐름 항목별 금액입니다. 정의와 기간이 다르므로 서로 더하거나 순수 사채 발행 총액으로 해석하지 않습니다.')}${panel('대형은행 자금조달 공시',table(['은행','수집한 공시 건수','실제 사채 발행 합계'],banks.map(s=>[s,num(inv.filter(e=>e.symbol===s).length),'미확정 · 원문 및 중복 거래 검토 필요'])),'424B2 구조화채권을 포함한 공시 목록입니다. 공시 건수는 사채 발행액이 아닙니다.')}${panel('자금조달 후보 문서',table(['기업','공시일','양식','검토 상태','근거'],candidates.slice(0,50).map(e=>[esc(e.symbol),esc(e.date),esc(e.form),'검토 대기',`<a href="${safeUrl(e.source_url)}" target="_blank" rel="noopener">원문 ↗</a>`])),`${candidates.length}개 후보. 약정·인출·상환·차환·중복 공시를 검증하기 전까지 총액에 합산하지 않습니다.`)}${panel('최근 기업 공시 · 최대 80건',table(['기업','공시일','양식','원문 상태','링크'],inv.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,80).map(e=>[esc(e.symbol),esc(e.date),esc(e.form),esc(e.document_status),`<a href="${safeUrl(e.source_url)}" target="_blank" rel="noopener">SEC ↗</a>`])))}`;}
function sources(){return panel('공식 데이터 수집 상태',db.sources.map(s=>`<div class="source-status"><div><h3>${esc(s.source)}</h3><p>관측 ${num(s.observations)}개 · 이벤트 ${num(s.events)}개 · 실행 ${esc(s.fetched_at)}</p>${(s.warnings||[]).map(w=>`<p>${esc(w)}</p>`).join('')}</div><span class="badge ${s.status==='ok'?'green':'gold'}">${state(s)}</span></div>`).join(''),'네트워크 실패 시 기존 관측값은 유지하며 실패 상태를 표시합니다. 저장 시점은 원자료 공표일과 다릅니다.')+panel('수집 범위와 해석',`<p>MOVE 제외. FRED · 연준 H.4.1/H.8 · 뉴욕연은 · 미 재무부 Fiscal Data · SEC EDGAR/N-MFP.</p><p class="help">원천 수집은 6시간 주기이며 공개 사이트는 기존 평일 18:25 발행 작업에서 갱신됩니다. 화면은 60초마다 최신 저장 파일을 확인합니다. AI 전용 회사채·CDS 스프레드와 사모대출 전체 거래 데이터는 미연결입니다.</p><p class="help">지표를 누르면 단위·관측일·기간·출처를 확인할 수 있습니다. 과거 데이터는 최신 정정본이며 수집 이전 시점의 빈티지 자료가 아닙니다.</p>`);}
function detail(id){const r=latest(id),s=sourceOf(r);document.getElementById('detail-body').innerHTML=`<h2>${esc(label(id))}</h2>${r?`<p><b>${display(r)}</b></p><p>관측일 ${esc(r.date)}<br>수집일 ${esc(r.fetched_at||r.metadata?.fetched_at||s?.fetched_at)}<br>보고기간 시작 ${esc(r.period_start)}<br>공시일 ${esc(r.filed)}<br>출처 상태 ${state(s)}</p><p><a href="${safeUrl(r.source_url)}" target="_blank" rel="noopener">공식 원자료 ↗</a></p><p class="help">${esc(r.basis||r.metadata?.interpretation||r.scope||'')}</p>`:'<p>아직 확보한 관측값이 없습니다.</p>'}`;document.getElementById('detail').showModal();}
function render(){const page=titles[location.hash.slice(1)]?location.hash.slice(1):'overview';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));document.getElementById('crumb').textContent=titles[page];const main=document.getElementById('main');if(!db){main.innerHTML='<div class="empty">실제 데이터 파일을 아직 불러오지 못했습니다. 파이프라인 수집 후 새로고침하세요.</div>';return;}main.innerHTML=`<div class="page-title"><div><h1>${titles[page]}</h1><p class="lead">공식 자료로 확인하는 신용 위험과 자금조달 여건</p></div><div class="date-tag">스냅샷 생성<b>${esc(db.generated_at?.replace('T',' ').slice(0,19))} UTC</b></div></div>${({overview,credit,treasury,funding,sources})[page]()}`;main.querySelectorAll('[data-series]').forEach(e=>e.onclick=()=>detail(e.dataset.series));main.querySelectorAll('[data-chart]').forEach(e=>e.onclick=()=>{selected=e.dataset.chart;render();});}
async function refresh(){try{const response=await fetch('/credit/data.json',{cache:'no-store'});if(!response.ok)throw Error(response.status);const next=await response.json();if(next.generated_at===db?.generated_at)return;db=next;series={};for(const r of db.observations)(series[r.series_id]??=[]).push(r);for(const rows of Object.values(series))rows.sort((a,b)=>a.date.localeCompare(b.date));document.querySelector('.status-link').textContent=`실데이터 · ${db.sources.filter(s=>s.status==='ok').length}/${db.sources.length} 소스 정상`;render();}catch{document.querySelector('.status-link').textContent='데이터 파일 연결 실패';if(!db)render();}}
document.getElementById('close-detail').onclick=()=>document.getElementById('detail').close();window.addEventListener('hashchange',render);refresh();setInterval(refresh,60000);
